package exception;

public class ArrayException {
	
	public static void main(String []args) {
		
		int [] arr = {10,34,38,28,59,22,4};
		
		int index = 4;
		try {
		
		System.out.println(arr[index]);
			
		}
		catch(ArrayIndexOutOfBoundsException e) {
			
			e.printStackTrace();
		}
		
		
	}
}
